using System.Security.Permissions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Internal;
using Microsoft.AspNetCore.Mvc;

public class ServiceResponseTests
{
    [Test]
    public void ServiceResponse_DefaultValues_ShouldBeSet()
    {
        // Arrange
        var serviceResponse = new ServiceResponse();
        ServiceResponse<object> ServiceResponseTyped = new ServiceResponse<object>();
        // Act

        // Assert
        Assert.Multiple(() =>
        {
            Assert.That(serviceResponse.Success, Is.True);
            Assert.That(serviceResponse.Message, Is.EqualTo(string.Empty));
            Assert.That(serviceResponse.ResponseStatus, Is.EqualTo(ServiceResponseStatus.Ok));
        });
        
        
        Assert.Multiple(() =>
        {
            Assert.That(ServiceResponseTyped.Success, Is.True);
            Assert.That(ServiceResponseTyped.Message, Is.EqualTo(string.Empty));
            Assert.That(ServiceResponseTyped.ResponseStatus, Is.EqualTo(ServiceResponseStatus.Ok));
            Assert.That(ServiceResponseTyped.Data, Is.Null);
        });
    }

    [Test]
    public void ServiceResponse_SetValues_ShouldBeSet()
    {
        // Arrange
        var serviceResponse = new ServiceResponse
        {
            Success = false,
            Message = "An error occurred",
            ResponseStatus = ServiceResponseStatus.Error
        };
        // Act

        // Assert
        Assert.Multiple(() =>
        {
            Assert.That(serviceResponse.Success, Is.False);
            Assert.That(serviceResponse.Message, Is.EqualTo("An error occurred"));
            Assert.That(serviceResponse.ResponseStatus, Is.EqualTo(ServiceResponseStatus.Error));
        });
    }

    [Test]
    public void ServiceResponsePaged_DefaultValues_ShouldBeSet()
    {
        // Arrange
        var serviceResponsePaged = new ServiceResponsePaged<object>(null, 1, 20, 0);
        // Act

        // Assert
        Assert.Multiple(() =>
        {
            Assert.That(serviceResponsePaged.Data, Is.Null);
            Assert.That(serviceResponsePaged.Page, Is.EqualTo(1));
            Assert.That(serviceResponsePaged.PageSize, Is.EqualTo(20));
            Assert.That(serviceResponsePaged.TotalCount, Is.EqualTo(0));
        });
    }

    [Test]
    public void ServiceResponsePaged_SetValues_ShouldBeSet()
    {
        // Arrange
        var data = new object();
        var serviceResponsePaged = new ServiceResponsePaged<object>(data, 2, 50, 100);
        // Act

        // Assert
        Assert.Multiple(() =>
        {
            Assert.That(serviceResponsePaged.Data, Is.EqualTo(data));
            Assert.That(serviceResponsePaged.Page, Is.EqualTo(2));
            Assert.That(serviceResponsePaged.PageSize, Is.EqualTo(50));
            Assert.That(serviceResponsePaged.TotalCount, Is.EqualTo(100));
        });
    }

    [Test]
    public void ExtendedController_SetResponse_ShouldSetStatusCode()
    {
        // Arrange
        var controller = new TestController();
        var response = new ServiceResponse();
        response.ResponseStatus = ServiceResponseStatus.Ok;

        // Act
        var result = controller.SetResponse(response);

        // Assert
        Assert.That(controller.Response.StatusCode, Is.EqualTo(200));
    }

    [Test]
    public void ExtendedController_ExceptionHandler_ShouldSetServiceResponse()
    {
        // Arrange
        var controller = new TestController();
        var response = new ServiceResponse();
        var exception = new Exception("An error occurred");

        // Act
        controller.ExceptionHandler.Handle(response, exception);
        
        // Assert
        Assert.Multiple(() =>
        {
            Assert.That(response.Success, Is.False);
            Assert.That(response.Message, Is.EqualTo("An error occurred, please contact support."));
            Assert.That(response.ResponseStatus, Is.EqualTo(ServiceResponseStatus.Error));
        });
    }
    
    [Test]
    public void TestExceptionHandlers()
    {
        var handler = new DebugExceptionHandler();
        var response = new ServiceResponse();
        var exception = new Exception("An error occurred", new Exception("Inner exception"));
        
        
        handler.Handle(response, exception);
        
        Assert.Multiple(() =>
        {
            Assert.That(response.Success, Is.False);
            Assert.That(response.Message.Trim(), Is.EqualTo("An error occurred\r\n\r\nInner exception"));
            Assert.That(response.ResponseStatus, Is.EqualTo(ServiceResponseStatus.Error));
        });
    }

    [Test]
    public void TestExceptionHandlers_WithNullResponse()
    {
        var testController = new TestController();
        
        var statuses = ServiceResponseStatus.GetValues<ServiceResponseStatus>();
        
        
        
        foreach (var status in statuses)
        {
            var response = testController.GetResponse(status);
            Assert.Multiple(() =>
            {
                Assert.That(response.ResponseStatus, Is.EqualTo(status));
                //  Assert.That(testController.Response.StatusCode, Is.EqualTo((int)status));
                //  For some reason this test fails, but it works in real life
            });
        }
    }
    
    
    private class TestController : ExtendedController
    {
        public new HttpResponse Response { get; set; } = new DefaultHttpResponse(new DefaultHttpContext());

        public TestController() : base(new PublicExceptionHandler())
        {
            ControllerContext = new ControllerContext
            {
                HttpContext = new DefaultHttpContext()
            };
        }

        public ServiceResponse GetResponse(ServiceResponseStatus status)
        {
            var response = new ServiceResponse
            {
                ResponseStatus = status
            };
            return SetResponse(response);
        }

    }
}